### ISSUE TITLE
Saving campaign state

### ISSUE THREAD

**Issue by artfoundry** [scottschiller/ArmorAlley#12]
Would be great if the game saved the missions a player had already completed (or at least the last one completed).  Maybe even scores too.

**Comment by scottschiller** [comment]
I've been meaning to patch in a "save state" for games underway, so you could have the option to resume if a browser window was accidentally or intentionally closed etc. There was a prior question about score tracking and perhaps a highscore leaderboard, with some discussion - see #8.

In the meantime, I've added a minimal save / recall for the battle selection drop down, and game difficulty.

**Comment by scottschiller** [comment]
I'm going to mark this one resolved, noting the game now remembers the last battle and difficulty played using localStorage - when available.

I've noted interest in scores and tracking. Rather than strictly "points" (and inventing some system for counting them), perhaps stats like shortest battle time (i.e., time to win), least units ordered / needed to win, least units / least helicopters lost, most enemy units destroyed etc.
