### ISSUE TITLE
Can't move the helicopter

### ISSUE THREAD

**Issue by JayLevine** [scottschiller/ArmorAlley#7]
When starting a new game on https://play.armor-alley.net/. The helicopter either stays on the pad, or pops up halfway and I can not move it. I can shoot and other keys, but not move the helo. Works fine on my desktop, but not on my 2.5-year-old Dell XPS 13 (9300) on either Chrome (just updated) or Firefox. 

I have a downloaded copy of AA V1.6.20220201 which works fine.

**Comment by scottschiller** [comment]
Whoops! 😅 Thanks for the report - I think I know what's going on, here.

AA V2.0 is a huge upgrade from V1.x under the hood, including revamped mouse and touch input handling. The game was previously not very playable on mobile or tablets; it's much better these days, but I had to refactor a lot of input handlers between mouse and touch events.

I'm going to guess there are no JS errors in your console, and this is about the fact your Dell XPS 13 has a touch-capable screen as well as a regular keyboard and mouse input.

I used a rather naïve approach to "detect" touch support, which I suspect is the root cause. Someone pointed this out a while back, who may have also had a laptop with a touch-capable screen. I made a note, and then I forgot about it. Whoops. 😅 

When you have a few, can you try loading up https://play.armor-alley.net/?dev=1 on that Dell XPS 13 and let me know if things work as expected? You should get the desktop UI version of the game (no visible touch controls like on mobile,) and keyboard and mouse input should work as expected.

Next test: if your touchscreen is enabled, ideally you should be able to touch and move the helicopter around the screen as well.

On mobile devices which I presume (currently) are "touch-first", the game shows touch controls on either side of the screen.
![AA - mobile touch controls UI](https://github.com/scottschiller/ArmorAlley/assets/174437/d143a217-a27d-4d43-9e56-fad91877a6db)

**Comment by JayLevine** [comment]
Hi,

Yes, my XPS 13 has a touch screen. The link with dev=1 works as expected, mouse controls! And the regular play. link allows touch controls.

Thanks, Jay

**Comment by scottschiller** [comment]
Excellent, thank you for confirming - and, thank you for playing my AA remake! I'll push a set of changes for this shortly.
